version: '3.0'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1
        container_name: elasticsearch
        # volumes:
        #     - ${DOCKER_DK_ELASTICSEARCH_DATA_DIR}:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - discovery.type=single-node
        #     - cluster.name=elasticsearch-cluster
        #     - bootstrap.memory_lock=true
        #     - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
        # ulimits:
        #     memlock:
        #         soft: -1
        #         hard: -1
        networks:
            - log-net

    logstash:
        image: docker.elastic.co/logstash/logstash-oss:6.7.1
        container_name: logstash
        expose:
            - "12201"
        ports:
            - "12201:12201"
            - "12201:12201/udp"
        volumes:
            - ./docker/logstash/pipeline/:/usr/share/logstash/pipeline/
        environment:
            TZ: Europe/Paris
        networks:
            - log-net
        depends_on:
          - elasticsearch

    kibana:
        image: docker.elastic.co/kibana/kibana-oss:6.7.1
        container_name: kibana
        ports:
           - "5601:5601"
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
        networks:
            - log-net
        depends_on:
          - elasticsearch

networks:
    log-net:
      driver: bridge
